### ISSUE TITLE
Auto-slug would be cool

### ISSUE THREAD

**Issue by pors** [smark-1/django-easy-faq#2]
I have a feature request: When leaving the slug field for a question empty, can you generate it by using the question with the spaces replaced by a `-`?

BTW, why do answers have a slug field?

**Comment by smark-1** [comment]
When leaving a slug blank this already generates a slug from random chars. This does not work through the django admin since it is still a required field. 
The slug field is not necessary but I like to expose the least amount of info to the end user as possible and a pk or slug most be exposed to allow voting for the answers.
To make this work 2 values in the models.py have to be changed. 
In the answer save method check if slug is null instead of pk.
In answer slug field set blank=True.
I don't think I have time to add this on the next couple weeks but if you make a pull request I can add it.

**Comment by pors** [comment]
I'm happy to give it a try, but I haven't contributed to a Django app before, so I'm not sure how to set that up? I can check out the source, but how do I use it in my project instead of the released version?

**Comment by pors** [comment]
Never mind, I figured it out :)
